# Project information
site_name: "{{cookiecutter.project_name}}"
site_author: "{{cookiecutter.full_name}}"
site_description: "{{cookiecutter.project_short_description}}"

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - header.autohide

# Page Tree
nav:
  - Home: README.md
  - Design: design/README.md
  - Hardware:
    - Overview: hardware/README.md
    - Mechanical: hardware/mechanical.md
    - Wiring: hardware/wiring.md
  - Software: software/README.md
  {% if cookiecutter.create_blog %}- Updates: blog/index.md{% endif %}
  {% if cookiecutter.create_changelog %}- Change Log: CHANGELOG.md{% endif %}

# Repository
repo_url: https://github.com/rebma-io/{{cookiecutter.project_slug}}
repo_name: rebma-io/{{ cookiecutter.project_slug }}

# Plugins
plugins:
  - search
  - macros
  - mermaid2
  {% if cookiecutter.create_blog %}
  - blog
  - rss:
      match_path: blog/posts/.*
      enabled: !ENV [CI, false]
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  {% endif %}

# Markdown Extensions
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.keys
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Extra Javascript
extra_javascript:
  - https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js

# Copyright
copyright: "Copyright {% now 'local', '%Y' %} {{cookiecutter.full_name}}"