# Project information
site_name: "{{ cookiecutter.project_name }}"
site_author: "{{ cookiecutter.full_name }}"
site_description: "{{ cookiecutter.project_short_description }}"

# Configuration
theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Fira Sans
    code: Fira Mono
  features:
    - navigation.tabs
    - header.autohide

# Page Tree
nav:
  - Home: README.md
  - Design: design/README.md
  - Hardware:
    - Overview: hardware/README.md
    - Mechanical: hardware/mechanical.md
    - Wiring: hardware/wiring.md
    - Datasheets: hardware/datasheets/README.md
  - Software: software/README.md
  {% if cookiecutter.create_blog == "y" %}- Updates: updates/index.md{% endif %}
  {% if cookiecutter.create_changelog == "y" %}- Changelog: CHANGELOG.md{% endif %}

# Repository
repo_url: https://github.com/{{ cookiecutter.github_org }}/{{ cookiecutter.project_slug }}
repo_name: {{ cookiecutter.github_org }}/{{ cookiecutter.project_slug }}

# Plugins
plugins:
  - search
  - macros:
      module_name: macros
  - mermaid2:
      javascript: https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js
  {% if cookiecutter.create_blog %}
  - blog:
      blog_dir: updates
      post_readtime: true
  - rss:
      match_path: updates/posts/.*
      enabled: !ENV [CI, false]
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  {% endif %}

# Markdown Extensions
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
        - name: wireviz
          class: wireviz
          format: !!python/name:wireviz_fences.fence_wireviz
  - pymdownx.keys
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Copyright
copyright: "Copyright {% now 'local', '%Y' %} {{ cookiecutter.full_name }}"